// Generated by packages/lovdacn/scripts/generate-design-system.cjs. Do not edit.

import { HugeiconsIcon } from '@hugeicons/react-native'
import GlyphActivity01Icon from "@hugeicons/core-free-icons/Activity01Icon"
import GlyphAppleIcon from "@hugeicons/core-free-icons/AppleIcon"
import GlyphArrowRight01Icon from "@hugeicons/core-free-icons/ArrowRight01Icon"
import GlyphNotification03Icon from "@hugeicons/core-free-icons/Notification03Icon"
import GlyphBookOpen02Icon from "@hugeicons/core-free-icons/BookOpen02Icon"
import GlyphRoboticIcon from "@hugeicons/core-free-icons/RoboticIcon"
import GlyphCalendar03Icon from "@hugeicons/core-free-icons/Calendar03Icon"
import GlyphChartUpIcon from "@hugeicons/core-free-icons/ChartUpIcon"
import GlyphTick02Icon from "@hugeicons/core-free-icons/Tick02Icon"
import GlyphArrowDown01Icon from "@hugeicons/core-free-icons/ArrowDown01Icon"
import GlyphArrowLeft01Icon from "@hugeicons/core-free-icons/ArrowLeft01Icon"
import GlyphUnfoldMoreIcon from "@hugeicons/core-free-icons/UnfoldMoreIcon"
import GlyphArrowUp01Icon from "@hugeicons/core-free-icons/ArrowUp01Icon"
import GlyphCancel01Icon from "@hugeicons/core-free-icons/Cancel01Icon"
import GlyphCommandIcon from "@hugeicons/core-free-icons/CommandIcon"
import GlyphCreditCardIcon from "@hugeicons/core-free-icons/CreditCardIcon"
import GlyphDollarSignIcon from "@hugeicons/core-free-icons/DollarSignIcon"
import GlyphMultiplicationSignCircleIcon from "@hugeicons/core-free-icons/MultiplicationSignCircleIcon"
import GlyphFrameIcon from "@hugeicons/core-free-icons/FrameIcon"
import GlyphImage01Icon from "@hugeicons/core-free-icons/Image01Icon"
import GlyphGitForkIcon from "@hugeicons/core-free-icons/GitForkIcon"
import GlyphHome01Icon from "@hugeicons/core-free-icons/Home01Icon"
import GlyphInformationCircleIcon from "@hugeicons/core-free-icons/InformationCircleIcon"
import GlyphDashboardSquare01Icon from "@hugeicons/core-free-icons/DashboardSquare01Icon"
import GlyphLifebuoyIcon from "@hugeicons/core-free-icons/LifebuoyIcon"
import GlyphLoading03Icon from "@hugeicons/core-free-icons/Loading03Icon"
import GlyphSidebarLeftIcon from "@hugeicons/core-free-icons/SidebarLeftIcon"
import GlyphCheckmarkCircle02Icon from "@hugeicons/core-free-icons/CheckmarkCircle02Icon"
import GlyphAlertCircleIcon from "@hugeicons/core-free-icons/AlertCircleIcon"
import GlyphSquareLock02Icon from "@hugeicons/core-free-icons/SquareLock02Icon"
import GlyphMail01Icon from "@hugeicons/core-free-icons/Mail01Icon"
import GlyphMenu01Icon from "@hugeicons/core-free-icons/Menu01Icon"
import GlyphMinusSignIcon from "@hugeicons/core-free-icons/MinusSignIcon"
import GlyphMoreHorizontalCircle01Icon from "@hugeicons/core-free-icons/MoreHorizontalCircle01Icon"
import GlyphPackageIcon from "@hugeicons/core-free-icons/PackageIcon"
import GlyphPieChartIcon from "@hugeicons/core-free-icons/PieChartIcon"
import GlyphPlusSignIcon from "@hugeicons/core-free-icons/PlusSignIcon"
import GlyphSearch01Icon from "@hugeicons/core-free-icons/Search01Icon"
import GlyphSettings01Icon from "@hugeicons/core-free-icons/Settings01Icon"
import GlyphSettings05Icon from "@hugeicons/core-free-icons/Settings05Icon"
import GlyphShoppingCart01Icon from "@hugeicons/core-free-icons/ShoppingCart01Icon"
import GlyphComputerTerminal01Icon from "@hugeicons/core-free-icons/ComputerTerminal01Icon"
import GlyphTrendingDownIcon from "@hugeicons/core-free-icons/TrendingDownIcon"
import GlyphTrendingUpIcon from "@hugeicons/core-free-icons/TrendingUpIcon"
import GlyphUserIcon from "@hugeicons/core-free-icons/UserIcon"
import GlyphUserGroupIcon from "@hugeicons/core-free-icons/UserGroupIcon"
import GlyphWallet01Icon from "@hugeicons/core-free-icons/Wallet01Icon"
import GlyphAlert02Icon from "@hugeicons/core-free-icons/Alert02Icon"
import * as React from 'react'

import type { IconAdapter } from '../semantic-icon-types'

const GLYPHS = {
  "activity": GlyphActivity01Icon,
  "apple": GlyphAppleIcon,
  "arrow-right": GlyphArrowRight01Icon,
  "bell": GlyphNotification03Icon,
  "book-open": GlyphBookOpen02Icon,
  "bot": GlyphRoboticIcon,
  "calendar": GlyphCalendar03Icon,
  "chart": GlyphChartUpIcon,
  "check": GlyphTick02Icon,
  "chevron-down": GlyphArrowDown01Icon,
  "chevron-down-icon": GlyphArrowDown01Icon,
  "chevron-left": GlyphArrowLeft01Icon,
  "chevron-right": GlyphArrowRight01Icon,
  "chevrons-up-down": GlyphUnfoldMoreIcon,
  "chevron-up": GlyphArrowUp01Icon,
  "chevron-up-icon": GlyphArrowUp01Icon,
  "close": GlyphCancel01Icon,
  "command": GlyphCommandIcon,
  "credit-card": GlyphCreditCardIcon,
  "dollar": GlyphDollarSignIcon,
  "error": GlyphMultiplicationSignCircleIcon,
  "frame": GlyphFrameIcon,
  "gallery": GlyphImage01Icon,
  "git-fork": GlyphGitForkIcon,
  "home": GlyphHome01Icon,
  "info": GlyphInformationCircleIcon,
  "layout-dashboard": GlyphDashboardSquare01Icon,
  "life-buoy": GlyphLifebuoyIcon,
  "loader": GlyphLoading03Icon,
  "loader-2": GlyphLoading03Icon,
  "panel-left": GlyphSidebarLeftIcon,
  "success-2": GlyphCheckmarkCircle02Icon,
  "alert-circle": GlyphAlertCircleIcon,
  "lock": GlyphSquareLock02Icon,
  "mail": GlyphMail01Icon,
  "menu": GlyphMenu01Icon,
  "minus": GlyphMinusSignIcon,
  "more-horizontal": GlyphMoreHorizontalCircle01Icon,
  "package": GlyphPackageIcon,
  "pie-chart": GlyphPieChartIcon,
  "plus": GlyphPlusSignIcon,
  "search": GlyphSearch01Icon,
  "settings": GlyphSettings01Icon,
  "settings-2": GlyphSettings05Icon,
  "shopping-cart": GlyphShoppingCart01Icon,
  "square-terminal": GlyphComputerTerminal01Icon,
  "success": GlyphCheckmarkCircle02Icon,
  "trending-down": GlyphTrendingDownIcon,
  "trending-up": GlyphTrendingUpIcon,
  "user": GlyphUserIcon,
  "users": GlyphUserGroupIcon,
  "wallet": GlyphWallet01Icon,
  "warning": GlyphAlert02Icon,
} as const

export const hugeiconsIconAdapter: IconAdapter = ({ name, size, color, className, strokeWidth, accessibilityLabel, decorative }) => (
  <HugeiconsIcon
    icon={GLYPHS[name]}
    size={size}
    color={color}
    strokeWidth={strokeWidth}
    className={className}
    accessibilityLabel={decorative ? undefined : accessibilityLabel}
    aria-hidden={decorative}
  />
)
