// Generated by packages/lovdacn/scripts/generate-design-system.cjs. Do not edit.

/// <reference path="../../../types/react-native-remix-icon.d.ts" />

import GlyphPulseLine from "react-native-remix-icon/src/icons/PulseLine"
import GlyphAppleLine from "react-native-remix-icon/src/icons/AppleLine"
import GlyphArrowRightLine from "react-native-remix-icon/src/icons/ArrowRightLine"
import GlyphNotification3Line from "react-native-remix-icon/src/icons/Notification3Line"
import GlyphBookOpenLine from "react-native-remix-icon/src/icons/BookOpenLine"
import GlyphRobotLine from "react-native-remix-icon/src/icons/RobotLine"
import GlyphCalendarLine from "react-native-remix-icon/src/icons/CalendarLine"
import GlyphLineChartLine from "react-native-remix-icon/src/icons/LineChartLine"
import GlyphCheckLine from "react-native-remix-icon/src/icons/CheckLine"
import GlyphArrowDownSLine from "react-native-remix-icon/src/icons/ArrowDownSLine"
import GlyphArrowLeftSLine from "react-native-remix-icon/src/icons/ArrowLeftSLine"
import GlyphArrowRightSLine from "react-native-remix-icon/src/icons/ArrowRightSLine"
import GlyphArrowUpDownLine from "react-native-remix-icon/src/icons/ArrowUpDownLine"
import GlyphArrowUpSLine from "react-native-remix-icon/src/icons/ArrowUpSLine"
import GlyphCloseLine from "react-native-remix-icon/src/icons/CloseLine"
import GlyphCommandLine from "react-native-remix-icon/src/icons/CommandLine"
import GlyphBankCardLine from "react-native-remix-icon/src/icons/BankCardLine"
import GlyphMoneyDollarCircleLine from "react-native-remix-icon/src/icons/MoneyDollarCircleLine"
import GlyphCloseCircleLine from "react-native-remix-icon/src/icons/CloseCircleLine"
import GlyphFocus3Line from "react-native-remix-icon/src/icons/Focus3Line"
import GlyphGalleryLine from "react-native-remix-icon/src/icons/GalleryLine"
import GlyphGitForkLine from "react-native-remix-icon/src/icons/GitForkLine"
import GlyphHomeLine from "react-native-remix-icon/src/icons/HomeLine"
import GlyphInformationLine from "react-native-remix-icon/src/icons/InformationLine"
import GlyphDashboardLine from "react-native-remix-icon/src/icons/DashboardLine"
import GlyphLifebuoyLine from "react-native-remix-icon/src/icons/LifebuoyLine"
import GlyphLoader4Line from "react-native-remix-icon/src/icons/Loader4Line"
import GlyphSideBarLine from "react-native-remix-icon/src/icons/SideBarLine"
import GlyphCheckboxCircleLine from "react-native-remix-icon/src/icons/CheckboxCircleLine"
import GlyphErrorWarningLine from "react-native-remix-icon/src/icons/ErrorWarningLine"
import GlyphLockLine from "react-native-remix-icon/src/icons/LockLine"
import GlyphMailLine from "react-native-remix-icon/src/icons/MailLine"
import GlyphMenuLine from "react-native-remix-icon/src/icons/MenuLine"
import GlyphSubtractLine from "react-native-remix-icon/src/icons/SubtractLine"
import GlyphMoreLine from "react-native-remix-icon/src/icons/MoreLine"
import GlyphBox3Line from "react-native-remix-icon/src/icons/Box3Line"
import GlyphPieChartLine from "react-native-remix-icon/src/icons/PieChartLine"
import GlyphAddLine from "react-native-remix-icon/src/icons/AddLine"
import GlyphSearchLine from "react-native-remix-icon/src/icons/SearchLine"
import GlyphSettingsLine from "react-native-remix-icon/src/icons/SettingsLine"
import GlyphEqualizer2Line from "react-native-remix-icon/src/icons/Equalizer2Line"
import GlyphShoppingCartLine from "react-native-remix-icon/src/icons/ShoppingCartLine"
import GlyphTerminalBoxLine from "react-native-remix-icon/src/icons/TerminalBoxLine"
import GlyphArrowDownLine from "react-native-remix-icon/src/icons/ArrowDownLine"
import GlyphArrowUpLine from "react-native-remix-icon/src/icons/ArrowUpLine"
import GlyphUserLine from "react-native-remix-icon/src/icons/UserLine"
import GlyphGroupLine from "react-native-remix-icon/src/icons/GroupLine"
import GlyphWalletLine from "react-native-remix-icon/src/icons/WalletLine"
import GlyphAlertLine from "react-native-remix-icon/src/icons/AlertLine"
import * as React from 'react'

import type { IconAdapter } from '../semantic-icon-types'

const GLYPHS = {
  "activity": GlyphPulseLine,
  "apple": GlyphAppleLine,
  "arrow-right": GlyphArrowRightLine,
  "bell": GlyphNotification3Line,
  "book-open": GlyphBookOpenLine,
  "bot": GlyphRobotLine,
  "calendar": GlyphCalendarLine,
  "chart": GlyphLineChartLine,
  "check": GlyphCheckLine,
  "chevron-down": GlyphArrowDownSLine,
  "chevron-down-icon": GlyphArrowDownSLine,
  "chevron-left": GlyphArrowLeftSLine,
  "chevron-right": GlyphArrowRightSLine,
  "chevrons-up-down": GlyphArrowUpDownLine,
  "chevron-up": GlyphArrowUpSLine,
  "chevron-up-icon": GlyphArrowUpSLine,
  "close": GlyphCloseLine,
  "command": GlyphCommandLine,
  "credit-card": GlyphBankCardLine,
  "dollar": GlyphMoneyDollarCircleLine,
  "error": GlyphCloseCircleLine,
  "frame": GlyphFocus3Line,
  "gallery": GlyphGalleryLine,
  "git-fork": GlyphGitForkLine,
  "home": GlyphHomeLine,
  "info": GlyphInformationLine,
  "layout-dashboard": GlyphDashboardLine,
  "life-buoy": GlyphLifebuoyLine,
  "loader": GlyphLoader4Line,
  "loader-2": GlyphLoader4Line,
  "panel-left": GlyphSideBarLine,
  "success-2": GlyphCheckboxCircleLine,
  "alert-circle": GlyphErrorWarningLine,
  "lock": GlyphLockLine,
  "mail": GlyphMailLine,
  "menu": GlyphMenuLine,
  "minus": GlyphSubtractLine,
  "more-horizontal": GlyphMoreLine,
  "package": GlyphBox3Line,
  "pie-chart": GlyphPieChartLine,
  "plus": GlyphAddLine,
  "search": GlyphSearchLine,
  "settings": GlyphSettingsLine,
  "settings-2": GlyphEqualizer2Line,
  "shopping-cart": GlyphShoppingCartLine,
  "square-terminal": GlyphTerminalBoxLine,
  "success": GlyphCheckboxCircleLine,
  "trending-down": GlyphArrowDownLine,
  "trending-up": GlyphArrowUpLine,
  "user": GlyphUserLine,
  "users": GlyphGroupLine,
  "wallet": GlyphWalletLine,
  "warning": GlyphAlertLine,
} as const

export const remixiconIconAdapter: IconAdapter = ({ name, size, color, className, accessibilityLabel, decorative }) => {
  const Component = GLYPHS[name]
  return (
    <Component
      width={size}
      height={size}
      fill={color}
      className={className}
      accessibilityLabel={decorative ? undefined : accessibilityLabel}
      aria-hidden={decorative}
    />
  )
}
