import fs from 'fs-extra'
import path from 'path'

import {
  FONT_MANIFEST,
  type PresetFont,
  type PresetFontHeading,
} from '../preset/index.js'

const FONT_IMPORT_MARKER = "import { useLvcnFonts } from '@/lib/lvcn-fonts'"
const FONT_READY_MARKER = 'const lvcnFontsReady = useLvcnFonts()'

type FontFaces = (typeof FONT_MANIFEST)[PresetFont]['faces']

export function packageNameFromSpecifier(specifier: string): string {
  if (!specifier.startsWith('@')) return specifier.split('@')[0]!
  const versionIndex = specifier.lastIndexOf('@')
  return versionIndex > specifier.indexOf('/') ? specifier.slice(0, versionIndex) : specifier
}

export function getExactFontPackage(font: PresetFont): string {
  const metadata = FONT_MANIFEST[font]
  return `${metadata.package}@${metadata.version}`
}

function importBlock(packageName: string, faces: FontFaces): string {
  return `import {\n  ${faces.regular},\n  ${faces.medium},\n  ${faces.semibold},\n  ${faces.bold},\n} from '${packageName}'`
}

function faceObject(name: string, faces: FontFaces): string {
  return `export const ${name} = {\n  regular: '${faces.regular}',\n  medium: '${faces.medium}',\n  semibold: '${faces.semibold}',\n  bold: '${faces.bold}',\n} as const`
}

export function writeProjectFontLoader(
  projectPath: string,
  font: PresetFont,
  fontHeading: PresetFontHeading = 'inherit'
): string {
  const body = FONT_MANIFEST[font]
  const headingKey: PresetFont = fontHeading === 'inherit' ? font : fontHeading
  const heading = FONT_MANIFEST[headingKey]
  const hasSrc = fs.existsSync(path.join(projectPath, 'src'))
  const target = path.join(projectPath, hasSrc ? 'src/lib/lvcn-fonts.ts' : 'lib/lvcn-fonts.ts')
  const imports = ["import { useFonts } from 'expo-font'", importBlock(body.package, body.faces)]
  if (headingKey !== font) imports.push(importBlock(heading.package, heading.faces))
  const loadedFaces = Array.from(new Set([
    ...Object.values(body.faces),
    ...Object.values(heading.faces),
  ]))
  const content = `// Generated by lovdaCN. Re-run \`lovda apply\` to change the selected fonts.\n${imports.join('\n')}\n\n${faceObject('LVCN_FONT_FACES', body.faces)}\n\n${faceObject('LVCN_HEADING_FONT_FACES', heading.faces)}\n\nexport function getLvcnFontStyle(className = '') {\n  const faces = className.includes('font-heading') ? LVCN_HEADING_FONT_FACES : LVCN_FONT_FACES\n  const fontFamily = className.includes('font-bold')\n    ? faces.bold\n    : className.includes('font-semibold')\n      ? faces.semibold\n      : className.includes('font-medium')\n        ? faces.medium\n        : faces.regular\n  return { fontFamily, fontWeight: 'normal' as const }\n}\n\nexport function useLvcnFonts() {\n  const [loaded, error] = useFonts({\n    ${loadedFaces.join(',\n    ')},\n  })\n  if (error) throw error\n  return loaded\n}\n`
  fs.ensureDirSync(path.dirname(target))
  fs.writeFileSync(target, content, 'utf8')
  return target
}

export function findProjectRootLayout(projectPath: string): string | null {
  const candidates = ['src/app/_layout.tsx', 'app/_layout.tsx', 'src/app/_layout.jsx', 'app/_layout.jsx']
  return candidates.map((file) => path.join(projectPath, file)).find((file) => fs.existsSync(file)) ?? null
}

export function wireProjectFontLoader(projectPath: string): string | null {
  const layoutPath = findProjectRootLayout(projectPath)
  if (!layoutPath) return null
  let content = fs.readFileSync(layoutPath, 'utf8')
  if (!content.includes(FONT_IMPORT_MARKER)) content = `${FONT_IMPORT_MARKER};\n${content}`
  if (!content.includes(FONT_READY_MARKER)) {
    const returnPattern = /\n(\s*)(return\b)/
    if (!returnPattern.test(content)) return null
    content = content.replace(
      returnPattern,
      `\n$1${FONT_READY_MARKER};\n$1if (!lvcnFontsReady) return null;\n\n$1$2`
    )
  }
  fs.writeFileSync(layoutPath, content, 'utf8')
  return layoutPath
}

export function configureProjectFonts(
  projectPath: string,
  font: PresetFont,
  fontHeading: PresetFontHeading = 'inherit'
) {
  const headingKey: PresetFont = fontHeading === 'inherit' ? font : fontHeading
  return {
    loaderPath: writeProjectFontLoader(projectPath, font, fontHeading),
    layoutPath: wireProjectFontLoader(projectPath),
    packageSpecifier: getExactFontPackage(font),
    packageSpecifiers: Array.from(new Set([getExactFontPackage(font), getExactFontPackage(headingKey)])),
  }
}

export function configureProjectFont(projectPath: string, font: PresetFont) {
  return configureProjectFonts(projectPath, font, 'inherit')
}
